### ISSUE TITLE
Examples need to be rebuilt with release modules

### ISSUE THREAD

**Issue by Chaircrusher** [matthewfriedrichs/HotBunnyManual#2]
Tried loading first example, got this error:
![image](https://user-images.githubusercontent.com/482621/35082244-57425cb4-fbde-11e7-8760-72bf8277764d.png)

**Comment by Chaircrusher** [comment]
For that matter I had to search to find the modules because they are under matthewfriedrichs and not "HotBunny" which you're led to believe is the name.

**Comment by Chaircrusher** [comment]
I got the module to load by changing the plugin name to "HotBunny" -- but it's very confusing because in the module menu it says "Matthew Friedrichs"

**Comment by matthewfriedrichs** [comment]
@Chaircrusher: You will now find HotBunnyExamples051.zip in the repository. These examples load with the latest version. The Slug had to be changed from "SOUv2.6.6_Friedrichs" to "HotBunny" as VCV expects the Slug to be the same as the plugin name. Needless to say, this is an issue that will not affect any future releases of Hot Bunny or my other plugins.

The plugins appear under Matthew Friedrichs as I will be releasing multiple plugins. They will all conveniently appear in that one folder.
